### ISSUE TITLE
Weird issue using SunEditor

### ISSUE THREAD

**Issue by svermaak** [mkhstar/suneditor-react#112]
Will update issue with more information as I uncover it
![image](https://user-images.githubusercontent.com/12259728/93725270-6fbfe000-fbcb-11ea-9c43-a771d000fa54.png)

**Comment by svermaak** [comment]
I have addressed this in my code but ultimately this happens if the initial value set on the component is null. I believe it should handle this and change it it <p><br /></p> or the like

**Comment by dirkwiggley** [comment]
I would add that when I initially create a component with SunEditor as a sub-component it is working fine so far. When I unmount the component with SunEditor in it and then mount it again I create SunEditor like this:
```
editor = <SunEditor 
                        setOptions={editorOptions} 
                        showToolbar={showToolbar}
                        hide={hide}
                        enable={enable} />
```
and I get the error mentioned above. I have not found a work-around for this. Here is the options I supply in the call:
```
       let editorOptions = 
        {
            "value": "",
            "mode": "classic",
            "toolbarContainer": "#custom_toolbar",
            "katex": "window.katex",
            "charCounter": true,
            "charCounterType": "char",
            "charCounterLabel": "String",
            "height": "",
            "minHeight": "200",
            "maxHeight": "800",
            "videoResizing": false,
            "videoHeightShow": false,
            "videoFileInput": false,
            "videoUrlInput": false,
            "videoRatioShow": false,
            "tabDisable": false,
            "templates": [
                {
                    "name": "Summary Sheet",
                    "html": "<div>Name</div><div>Race: </div><div>AGI: SMA: SPI: STR: VIG: | Pace: Parry: Toughness</div><div>Abilities: </div><div>Edges: </div><div>Hindrances: </div><div>Skills: </div><div>Powers: </div>"
                },
                {
                    "name": "Template-2",
                    "html": "<p>HTML source2</p>"
                }
            ],
            "buttonList": [
                [
                    "undo",
                    "redo",
                    "font",
                    "fontSize",
                    "formatBlock",
                    "paragraphStyle",
                    "blockquote",
                    "bold",
                    "underline",
                    "italic",
                    "strike",
                    "subscript",
                    "superscript",
                    "fontColor",
                    "hiliteColor",
                    "textStyle",
                    "removeFormat",
                    "outdent",
                    "indent",
                    "align",
                    "horizontalRule",
                    "list",
                    "lineHeight",
                    "table",
                    "link",
                    "image",
                    "fullScreen",
                    "showBlocks",
                    "codeView",
                    "preview",
                    "print",
                    "save",
                    "template"
                ]
            ],
            // "lang": SUNEDITOR_LANG.en,
            "lang(In nodejs)": "en",
            callBackSave: this.callBackSave
        }
```

Note that I have commented out _"lang" L SUNEDITOR_LANG.en_ as I get the error `` 'SUNEDITOR_LANG' is not defined  no-undef`` when I try to use it.

Lastly the values I use for _showToolbar_ , _hide_ , and _enable_ are all false.

**Comment by dirkwiggley** [comment]
Update: I'm in my component's **render** method I create a SunEditor with one of two sets of options:
```
        if (contents !== null && contents !== '') {
            editor = <SunEditor 
                        setOptions={editorOptions} 
                        setContents={contents} 
                        showToolbar={showToolbar}
                        hide={hide}
                        enable={enable} />
        } else {
            editor = <SunEditor 
                        setOptions={editorOptions}
                        setContents={'<p><br /></p>'}
                        showToolbar={showToolbar}
                        hide={hide}
                        enable={enable} />
        }
```
Previously the else condition used _setContents={null}_ and that was what on my side was causing the exception inside the SunEditor. So I changed that per the suggestion in the top of the thread to _setContents={'<p><br /></p>'}_ and it doesn't crash. However it still shows the contents it had previously been displaying and not an essentially blank editor.
